var config = {
  apiUrl: "https://admin.cryptocurve.xyz/",
  apiHeader: "Basic QTEyNTk3OEY3NkYxODA3NkVBMkQzNjY2QzAzOTE1QzM1OTVFODc5RUE2MEQ3NTQzNjg2NEJFMUE2MDJCNjA4QzpGMDNFODc5M0FBMjk4OTRFMkVBRjc1QUFERjY0MDA5RUFFQTk5MjMyMzI5OUU4M0RCODYwOTU4MENGMDBFQzJB"
};

module.exports = config;
